name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Cambia la versión de PHP según tus necesidades

      - name: Build your PHP files
        run: php .  # Cambia esto al comando que compila tus archivos PHP

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Cambia esto a la carpeta donde se generan los archivos PHP
