name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Cambia a la versi칩n de PHP que est치s utilizando

      - name: Build site
        run: php .  # Cambia a tu comando de compilaci칩n

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Cambia al directorio donde se encuentran los archivos est치ticos generados
